// Seed base of real-shaped Tashkent B2B companies for barter matching.
// On the MVP this is administered by hand (per BRD §6). The AI matcher picks
// from THIS list — it does not invent partners — which is the data moat.
// Each entry: what the company offers ↔ what it seeks, plus category + contact.

export const COMPANIES = [
  {
    id: "bellissimo",
    name: "Bellissimo",
    about: "Сеть пиццерий, 40 точек по Ташкенту, аудитория 18–35 лет.",
    category: "food",
    gives: "QR-столы, экраны в залах, промо в соцсетях (120k подписчиков), место под ивенты.",
    seeks: "Медиа-охваты под запуск сезонного меню, коллаборации с брендами напитков.",
    contact: "partners@bellissimo.uz",
  },
  {
    id: "korzinka",
    name: "Korzinka",
    about: "Крупнейшая сеть супермаркетов, трафик семей и офисных сотрудников.",
    category: "retail",
    gives: "Полки под сэмплинг, экраны у касс, вкладыши в чеки, площадки для активаций.",
    seeks: "Готовый контент для соцсетей, кейтеринг для корпоративных событий, digital-охваты.",
    contact: "bd@korzinka.uz",
  },
  {
    id: "uzum",
    name: "Uzum Market",
    about: "Маркетплейс и финтех, молодая цифровая аудитория по всей стране.",
    category: "tech",
    gives: "Баннеры в приложении, пуш-рассылки, промокоды, совместные акции.",
    seeks: "Офлайн-точки для выдачи и промо, амбассадоров, ивент-площадки.",
    contact: "growth@uzum.uz",
  },
  {
    id: "makon-mall",
    name: "Makon Mall",
    about: "Торговый центр в центре Ташкента, высокий пешеходный трафик по выходным.",
    category: "realestate",
    gives: "Атриум под ивенты, рекламные конструкции, парковка, зоны фотозон.",
    seeks: "Артисты и ведущие для событий, кейтеринг, digital-продвижение мероприятий.",
    contact: "events@makonmall.uz",
  },
  {
    id: "gymzone",
    name: "GymZone",
    about: "Сеть фитнес-клубов, аудитория 20–40 лет, интерес к здоровью и спорту.",
    category: "sport",
    gives: "Экраны в залах, сэмплинг спортпита, доступ к аудитории, коллаборации тренеров.",
    seeks: "Здоровые напитки и питание для баров, спортивная экипировка, медиа-партнёры.",
    contact: "marketing@gymzone.uz",
  },
  {
    id: "streamliga",
    name: "StreamLiga",
    about: "Стриминговая платформа спортивных трансляций, фанаты футбола и UFC.",
    category: "media",
    gives: "Рекламные слоты в трансляциях, интеграции комментаторов, аудитория болельщиков.",
    seeks: "Спонсоры трансляций, площадки для просмотров матчей, призовой фонд для розыгрышей.",
    contact: "sales@streamliga.uz",
  },
  {
    id: "coffee-lab",
    name: "Coffee Lab",
    about: "Сеть кофеен спешелти, креативная аудитория, фрилансеры и студенты.",
    category: "food",
    gives: "Стаканы под брендинг, стойки с флаерами, площадки для мини-ивентов и лекций.",
    seeks: "Контент-съёмка, дизайн-услуги, коллаборации с книжными и коворкингами.",
    contact: "hello@coffeelab.uz",
  },
  {
    id: "workhub",
    name: "WorkHub",
    about: "Сеть коворкингов, стартапы, IT-специалисты и малый бизнес.",
    category: "realestate",
    gives: "Залы под мероприятия, места для резидентов, экраны, доступ к комьюнити.",
    seeks: "Кофейни-партнёры, провайдеры софта, образовательные программы, спикеры.",
    contact: "community@workhub.uz",
  },
  {
    id: "medion-clinic",
    name: "Medion Clinic",
    about: "Частная медицинская клиника, платёжеспособная аудитория 30–55 лет.",
    category: "health",
    gives: "Экраны в холлах, буклеты, бесплатные чек-апы как призы, экспертный контент врачей.",
    seeks: "Медиа-охваты, коллаборации с фитнес и wellness-брендами, digital-продвижение.",
    contact: "pr@medion.uz",
  },
  {
    id: "avtoluxe",
    name: "AvtoLuxe",
    about: "Автосалон и сервис, аудитория состоятельных мужчин 30–50 лет.",
    category: "auto",
    gives: "Тест-драйвы как призы, площадка салона под ивенты, брендированные авто для съёмок.",
    seeks: "Премиальные бренды для кросс-промо, event-организаторов, медиа с деловой аудиторией.",
    contact: "vip@avtoluxe.uz",
  },
  {
    id: "bookcity",
    name: "BookCity",
    about: "Сеть книжных магазинов, читающая аудитория, семьи и студенты.",
    category: "retail",
    gives: "Полки под выкладку, площадки для встреч и автограф-сессий, аудитория лояльных клиентов.",
    seeks: "Кофейни-партнёры, издательства, спикеры и авторы, digital-продвижение событий.",
    contact: "events@bookcity.uz",
  },
  {
    id: "digitalwave",
    name: "DigitalWave",
    about: "Диджитал-агентство, produces контент и таргетированную рекламу.",
    category: "media",
    gives: "SMM-продвижение, продакшн видео, дизайн, таргет-бюджеты по бартеру.",
    seeks: "Офлайн-площадки для съёмок, доступ к продуктам для контента, ивент-партнёры.",
    contact: "hi@digitalwave.uz",
  },
  {
    id: "freshjuice",
    name: "Fresh & Juice",
    about: "Бренд свежих соков и смузи, точки в ТЦ и фитнес-клубах.",
    category: "food",
    gives: "Продукция для сэмплинга и призов, брендированные стойки, коллаборации вкусов.",
    seeks: "Точки размещения (фитнес, коворкинги, ивенты), медиа-охваты, дизайн упаковки.",
    contact: "partners@freshjuice.uz",
  },
  {
    id: "eventpro",
    name: "EventPro",
    about: "Агентство организации мероприятий, корпоративы и фестивали.",
    category: "events",
    gives: "Организация и техническое обеспечение ивентов, ведущие, сцена и свет по бартеру.",
    seeks: "Площадки, кейтеринг, спонсоры призового фонда, медиа-освещение событий.",
    contact: "book@eventpro.uz",
  },
  {
    id: "techstore",
    name: "TechStore",
    about: "Сеть магазинов электроники, аудитория гиков и молодёжи.",
    category: "tech",
    gives: "Гаджеты как призы, зоны демо в магазинах, экраны, аудитория tech-энтузиастов.",
    seeks: "Контент-креаторов, ивент-площадки, коллаборации с играми и киберспортом.",
    contact: "promo@techstore.uz",
  },
  {
    id: "cybera",
    name: "Cybera Arena",
    about: "Киберспортивная арена, турниры и стримы, аудитория геймеров 16–28.",
    category: "sport",
    gives: "Площадка под турниры, стримы с брендингом, аудитория геймеров, зоны активаций.",
    seeks: "Энергетики и снеки, спонсоры призов, техника для апгрейда, медиа-партнёры.",
    contact: "sponsors@cybera.uz",
  },
  {
    id: "beautyhouse",
    name: "Beauty House",
    about: "Сеть салонов красоты, женская аудитория 20–45 лет.",
    category: "beauty",
    gives: "Сертификаты как призы, зоны в салонах, аудитория в соцсетях, коллаборации мастеров.",
    seeks: "Косметические бренды, фотографы, digital-продвижение, ивенты для клиентов.",
    contact: "collab@beautyhouse.uz",
  },
  {
    id: "kidsland",
    name: "KidsLand",
    about: "Сеть детских развлекательных центров, семьи с детьми 3–12 лет.",
    category: "entertainment",
    gives: "Площадки под детские ивенты, билеты как призы, аудитория родителей, зоны брендинга.",
    seeks: "Детские бренды (питание, одежда, игрушки), аниматоры, медиа для семей.",
    contact: "events@kidsland.uz",
  },
  {
    id: "hotelgrand",
    name: "Grand Hotel",
    about: "Бизнес-отель в центре, деловые путешественники и конференции.",
    category: "hospitality",
    gives: "Залы под конференции, номера как призы, зоны для съёмок, деловая аудитория.",
    seeks: "Организаторы бизнес-событий, кейтеринг премиум, digital-продвижение, спикеры.",
    contact: "mice@grandhotel.uz",
  },
  {
    id: "radiofm",
    name: "Radio FM101",
    about: "Городская FM-радиостанция, широкий охват автомобилистов.",
    category: "media",
    gives: "Рекламные слоты, упоминания ведущих, розыгрыши в эфире, широкий охват.",
    seeks: "Призовой фонд для розыгрышей, ивент-площадки, партнёры для рубрик.",
    contact: "reklama@fm101.uz",
  },
  {
    id: "sportmax",
    name: "SportMax",
    about: "Магазин спортивной экипировки и одежды, активная аудитория.",
    category: "sport",
    gives: "Экипировка как призы, брендинг в магазинах, аудитория спортсменов-любителей.",
    seeks: "Спортивные события и клубы, фитнес-партнёры, медиа-освещение, амбассадоры.",
    contact: "team@sportmax.uz",
  },
  {
    id: "artgallery",
    name: "Art Space",
    about: "Современная арт-галерея и креативное пространство, творческая аудитория.",
    category: "culture",
    gives: "Пространство под выставки и ивенты, аудитория креативного класса, фотозоны.",
    seeks: "Спонсоры выставок, напитки и кейтеринг для вернисажей, медиа-партнёры.",
    contact: "curate@artspace.uz",
  },
  {
    id: "edulab",
    name: "EduLab",
    about: "Образовательный центр, курсы IT и языков, молодёжь 16–30 лет.",
    category: "education",
    gives: "Аудитория студентов, аудитории под ивенты, экспертные спикеры, соцсети.",
    seeks: "IT-компании для карьерных дней, коворкинги, техника, медиа-охваты.",
    contact: "partners@edulab.uz",
  },
  {
    id: "greenmarket",
    name: "Green Market",
    about: "Магазин здорового и эко-питания, осознанная аудитория 25–45 лет.",
    category: "food",
    gives: "Полки под эко-бренды, дегустации, аудитория ЗОЖ, коллаборации рецептов.",
    seeks: "Фитнес и wellness-партнёры, эко-упаковка, контент-съёмка, ивенты о здоровье.",
    contact: "eco@greenmarket.uz",
  },
];

export function companiesForPrompt(excludeName) {
  return COMPANIES.filter(
    (c) => !excludeName || c.name.toLowerCase() !== excludeName.trim().toLowerCase()
  ).map(
    (c) =>
      `- ${c.name} [${c.category}] — ${c.about}\n  Отдаёт: ${c.gives}\n  Ищет: ${c.seeks}\n  Контакт: ${c.contact}`
  ).join("\n");
}
